# This is a basic workflow to help you get started with Actions

name: DockerIMG_Build&Publish

# Controls when the workflow will run
on:
  push:
    branches: [ "Development", "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
        
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Project2_Server.API/
          file: ./Project2_Server.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/Team_Pizza:latest
          
          
        
      
