# This is a basic workflow to help you get started with Actions

name: API to Development Auto Push

# Controls when the workflow will run
on:
  # Will run every day at 0:25 UTC -8 
  schedule:
    - cron: '25 8 * * *'
  workflow_dispatch:
  
env:
  branch: API
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 my-job:
  name: Push API to Development
  runs-on: ubuntu-latest
  steps:
      - run: | 
         gh pr create --fill --head
      
         
