# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Will run every day at 0:25 UTC -8 
  schedule:
    - cron: '25 8 * * *

  workflow_dispatch:
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create -B Development -H API --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
